name: test

on: [push, pull_request]
  
jobs:
 build-1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        flag: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    timeout-minutes: 180
    steps:
    - uses: actions/checkout@v2
    - name: kune
      run: |
        sudo apt-get update -y
